#!/bin/bash

jarfile=start
find . -type f -name "*.jar" | (
     while [ ! -z "$jarfile" ]; do
           read jarfile
  	   echo "============== $jarfile =============="
	   jar tvf $jarfile
     done
)
